name: Deploying Lambda
on:
  push:
    branches:
      - main
jobs:
  lambda1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - run: zip -j index.zip ./index.js
      - run: aws lambda update-function-code --function-name=http-sample-gene-test --zip-file=fileb://index.zip
